Nov 26 20:22:12.107 INFO Done processing trigger, gas_used: 387515148, data_source: ConditionalTokens, handler: handleTransferBatch, total_ms: 4, transaction: 0x9613…4867, address: 0xceaf…c0ce, signature: TransferBatch(indexed address,indexed address,indexed address,uint256[],uint256[]), sgd: 5, subgraph_id: QmQWv4GfiqWBM4CqNu5ZKxcYiy7D7HiohojcMtwwR2CHox, component: SubgraphInstanceManager
Nov 26 20:22:12.108 INFO Applying 15 entity operation(s), block_hash: 0x2b1231a390974633a4bc4050127554741b97f3e0bf0dd414b3641a1ce72d4a45, block_number: 34000009, sgd: 5, subgraph_id: QmQWv4GfiqWBM4CqNu5ZKxcYiy7D7HiohojcMtwwR2CHox, component: SubgraphInstanceManager
Nov 26 20:22:12.108 ERRO Subgraph error 1/1, code: SubgraphSyncingFailure, error: transaction 9613e9c2f96bf27a3250c4814674d4569fbb7e5f8c8d061ffca7a6eb4b9a4867: error while executing at wasm backtrace:            0: 0x49c5 - <unknown>!generated/ConditionalTokens/ConditionalTokens/ConditionalTokens#getCollectionId          1: 0x5a55 - <unknown>!src/positions/operateOnSubtree            2: 0x656a - <unknown>!src/positions/handlePositionSplit: Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 675, column 7, with message: Call reverted, probably because an `assert` or `require` in the contract failed, consider using `try_getCollectionId` to handle this in the mapping. in handler `handlePositionSplit` at block #34000009 (2b1231a390974633a4bc4050127554741b97f3e0bf0dd414b3641a1ce72d4a45), block_hash: 0x2b1231a390974633a4bc4050127554741b97f3e0bf0dd414b3641a1ce72d4a45, block_number: 34000009, sgd: 5, subgraph_id: QmQWv4GfiqWBM4CqNu5ZKxcYiy7D7HiohojcMtwwR2CHox, component: SubgraphInstanceManager
Nov 26 20:22:12.112 ERRO Subgraph instance failed to run: transaction 9613e9c2f96bf27a3250c4814674d4569fbb7e5f8c8d061ffca7a6eb4b9a4867: error while executing at wasm backtrace:            0: 0x49c5 - <unknown>!generated/ConditionalTokens/ConditionalTokens/ConditionalTokens#getCollectionId          1: 0x5a55 - <unknown>!src/positions/operateOnSubtree            2: 0x656a - <unknown>!src/positions/handlePositionSplit: Mapping aborted at ~lib/@graphprotocol/graph-ts/chain/ethereum.ts, line 675, column 7, with message: Call reverted, probably because an `assert` or `require` in the contract failed, consider using `try_getCollectionId` to handle this in the mapping. in handler `handlePositionSplit` at block #34000009 (2b1231a390974633a4bc4050127554741b97f3e0bf0dd414b3641a1ce72d4a45), code: SubgraphSyncingFailure, sgd: 5, subgraph_id: QmQWv4GfiqWBM4CqNu5ZKxcYiy7D7HiohojcMtwwR2CHox, component: SubgraphInstanceManager
Nov 26 20:22:12.311 INFO Scanning blocks [34000010, 34000019], range_size: 10, sgd: 5, subgraph_id: QmQWv4GfiqWBM4CqNu5ZKxcYiy7D7HiohojcMtwwR2CHox, component: BlockStream